In [1]:
import pandas as pd

In [2]:
df=pd.read_csv(r"C:\Users\shish\OneDrive\Desktop\python code\machine learning\7_logistic_reg\HR_comma_sep.csv")
df.head()

,satisfaction_level,last_evaluation,number_project,average_montly_hours,time_spend_company,Work_accident,left,promotion_last_5years,Department,salary
0,0.38,0.53,2,157,3,0,1,0,sales,low
1,0.80,0.86,5,262,6,0,1,0,sales,medium
2,0.11,0.88,7,272,4,0,1,0,sales,medium
3,0.72,0.87,5,223,5,0,1,0,sales,low
4,0.37,0.52,2,159,3,0,1,0,sales,low

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14999 entries, 0 to 14998
Data columns (total 10 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   satisfaction_level     14999 non-null  float64
 1   last_evaluation        14999 non-null  float64
 2   number_project         14999 non-null  int64
 3   average_montly_hours   14999 non-null  int64
 4   time_spend_company     14999 non-null  int64
 5   Work_accident          14999 non-null  int64
 6   left                   14999 non-null  int64
 7   promotion_last_5years  14999 non-null  int64
 8   Department             14999 non-null  object
 9   salary                 14999 non-null  object
dtypes: float64(2), int64(6), object(2)
memory usage: 1.1+ MB

In [4]:
df.isnull().sum()

satisfaction_level       0
last_evaluation          0
number_project           0
average_montly_hours     0
time_spend_company       0
Work_accident            0
left                     0
promotion_last_5years    0
Department               0
salary                   0
dtype: int64

In [ ]:
salary_dummies=pd.get_dummies(df.salary,prefix='salary')
salary_dummies.head()

In [9]:
df=pd.concat([df,salary_dummies],axis=1)
df

,satisfaction_level,last_evaluation,number_project,average_montly_hours,time_spend_company,Work_accident,left,promotion_last_5years,Department,salary,salary_high,salary_low,salary_medium
0,0.38,0.53,2,157,3,0,1,0,sales,low,False,True,False
1,0.80,0.86,5,262,6,0,1,0,sales,medium,False,False,True
2,0.11,0.88,7,272,4,0,1,0,sales,medium,False,False,True
3,0.72,0.87,5,223,5,0,1,0,sales,low,False,True,False
4,0.37,0.52,2,159,3,0,1,0,sales,low,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
14994,0.40,0.57,2,151,3,0,1,0,support,low,False,True,False
14995,0.37,0.48,2,160,3,0,1,0,support,low,False,True,False
14996,0.37,0.53,2,143,3,0,1,0,support,low,False,True,False
14997,0.11,0.96,6,280,4,0,1,0,support,low,False,True,False
14998,0.37,0.52,2,158,3,0,1,0,support,low,False,True,False

In [ ]:
df.drop('salary',axis=1,inplace=True)

In [18]:
df.head()

,satisfaction_level,last_evaluation,number_project,average_montly_hours,time_spend_company,Work_accident,left,promotion_last_5years,Department,salary_high,salary_low,salary_medium
0,0.38,0.53,2,157,3,0,1,0,sales,False,True,False
1,0.80,0.86,5,262,6,0,1,0,sales,False,False,True
2,0.11,0.88,7,272,4,0,1,0,sales,False,False,True
3,0.72,0.87,5,223,5,0,1,0,sales,False,True,False
4,0.37,0.52,2,159,3,0,1,0,sales,False,True,False

In [ ]:
subdf = df[['satisfaction_level','average_montly_hours','promotion_last_5years','salary']]
subdf.head()

In [35]:
df.drop(['last_evaluation',	'number_project',	'time_spend_company',	'Work_accident',	'Department'],axis=1,inplace=True)

In [53]:
X=df.drop(['left','salary_high'],axis=1)

In [54]:
y=df.left

In [55]:

X.head()

,satisfaction_level,average_montly_hours,promotion_last_5years,salary_low,salary_medium
0,0.38,157,0,True,False
1,0.80,262,0,False,True
2,0.11,272,0,False,True
3,0.72,223,0,True,False
4,0.37,159,0,True,False

In [56]:
y

0        1
1        1
2        1
3        1
4        1
        ..
14994    1
14995    1
14996    1
14997    1
14998    1
Name: left, Length: 14999, dtype: int64

In [57]:
y.value_counts()

left
0    11428
1     3571
Name: count, dtype: int64

In [63]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3)

In [64]:
from sklearn.linear_model import LinearRegression

model=LinearRegression()

In [65]:
model.fit(X_train,y_train)

LinearRegression()

In [66]:
model.predict(X_test)

array([0.24657699, 0.50118615, 0.15997525, ..., 0.16676289, 0.00757477,
       0.22082324])

In [67]:
model.score(X_test,y_test)

0.1897683211517478